cienfuegosexotics/cienfuegosexotics/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path("", include("mainapp.urls")),
    path("admin/", admin.site.urls),
]

cienfuegosexotics/mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("peppers/", views.peppers, name="peppers"),
    path("learning/", views.learning, name="learning"),
    path("mantises/", views.mantises, name="mantises"),
    path("tomatoes/", views.tomatoes, name="tomatoes"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
]

cienfuegosexotics/mainapp/models.py
from django.db import models

# Create your models here.

cienfuegosexotics/mainapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {}
    return render(request, "mainapp/index.html", context)
    
def about(request):
    context = {}
    return render(request, "mainapp/aboutus.html", context)

def tomatoes(request):
    context = {}
    return render(request, "mainapp/tomatoes.html", context)

def mantises(request):
    context = {}
    return render(request, "mainapp/mantises.html", context)

def peppers(request):
    context = {}
    return render(request, "mainapp/peppers.html", context)

def contact(request):
    context = {}
    return render(request, "mainapp/contact.html", context)

def learning(request):
    context = {}
    return render(request, "mainapp/learning.html", context)

cienfuegosexotics/mainapp/templates/mainapp/aboutus.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block body %}

<section id="header" class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center text-white">
        <h1 class="text-center text-wrap display-1">About Us</h1>
      </div>
    </div>
  </div>
</section>

<section id="contact" class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8 offset-md-2">
        <h2 class="display-3 text-center">And Now For Something Completely Different...</h2>
        <p>We have a small garden that we use to grow exotic plants. We always have an excess of GREAT PLANTS, so we've set up this website so we can share them with you. </p>
        <p>We always grow exciting vegetables such as tiny tomatoes, ultra hot peppers, purple potatoes, and weird cucumbers. Have a look though the website, and be sure to check out our youtube channel so you can see what we're talking about.</p>
        <p>Our plants are started from seed indoors in the middle of winter so they're big and healthy when spring finally rolls around. If you're thinking about starting a garden - and you want an interesting plant that you won't find in any other store - give us a call!</p>
      </div>
    </div>
  </div>
</section>



{% endblock %}


{% block updateActive %}
   <script>
    $(document).ready(function() {
            var currentPage= $( "#about_page_nav_item" );    
            .addClass( "active" );
        });
    </script>
{% endblock %}

cienfuegosexotics/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">



    <script src=" https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo
        " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js " integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49
        " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js " integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T
        " crossorigin="anonymous "></script>

    <link rel="stylesheet" href="{% static 'mainapp/css/style.css' %}">

    <link rel="shortcut icon" type="image/png" href="{% static 'mainapp/favicon/favicon.ico' %}"/>

    <title>Cienfuegos Exotics</title>
</head>


<body>

  <nav class="navbar navbar-expand-md custom-navbar" id="main-nav">
      <div class="container">
        <a href="{% url 'mainapp:index' %}" class="navbar-brand">
          <img src="{% static 'mainapp/img/url_logo.png' %}" height="38" alt="logo">
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">     
            <li class="mr-auto nav-item" id="contact_page_nav_item">
              <a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a>
            </li>
            <li class="mr-auto nav-item" id="about_page_nav_item">
              <a href="{% url 'mainapp:about' %}" class="nav-link">About</a>
            </li>
            <li class="mr-auto nav-item" id="about_page_nav_item">
          <a href="https://www.youtube.com/@cienfuegosexotics" class="nav-link" target="_blank">
            <i class="fab fa-youtube fa-1x"></i>
          </a>
            </li>
   
            </a>    
          </ul>
        </div>
      </div>
  </nav>

    {% block body %}
    {% endblock %}
    
    <footer id="main-footer" class="py-5 mathtestmakerGreenBG">
      <div class="container">
        <div class="row text-center">
          <div class="col-12 ml-auto">
            <p class="lead">Copyright &copy; <span id="year"></span></p>
          </div>
        </div>
      </div>
    </footer>
    



    <!-- Update the copyright date -->
    <script>
      // Get the current year for the copyright
      $('#year').text(new Date().getFullYear());
    
      // Init Scrollspy
      $('body').scrollspy({ target: '#main-nav' });
    
      // Smooth Scrolling
      $("#main-nav a").on('click', function (event) {
        if (this.hash !== "") {
          event.preventDefault();
    
          const hash = this.hash;
    
          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 800, function () {
    
            window.location.hash = hash;
          });
        }
      });
    
    </script>

    {% block updateActive %}
    {% endblock %}

</body>

cienfuegosexotics/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block body %}

<section id="header" class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center text-white">
        <h1 class="text-center text-wrap display-1">Get In Touch</h1>
      </div>
    </div>
  </div>
</section>

<section id="contact" class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="display-3">Call or Text!</h2>
        <h2 class="display-3">551-300-9323</h2>
        <p class="display-3">We're located right in front of Union City High School</p>
      </div>
    </div>
  </div>
</section>



{% endblock %}


{% block updateActive %}
   <script>
    $(document).ready(function() {
            var currentPage= $( "#about_page_nav_item" );    
            .addClass( "active" );
        });
    </script>
{% endblock %}

cienfuegosexotics/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block body %}
<body>

<!-- Header Section -->
<section id="header">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="display-1 pt-5 text-white">J. Cienfuegos & Sons</h1>
        <h2 id="exoticspeciesheadertext" class="display-3 mt-3 mb-1">Exotic Species</h2>
        <h3 class="display-4 my-1 text-white">est. 2021 &#8226; Union City, NJ</h3>
        <h3 class="display-4 my-3 pb-3 text-white">551-300-9323</h3>
      </div>
    </div>
  </div>
</section>

<!-- $10 Tier Section -->
<section id="forsaleyoungplant" class="py-5">
  <div class="container">

    <div class="row">
      <div class="col-12 text-center">
        <h2 class="display-3">2 for $10 Tier</h2>
        <h3 class="display-4">Grown from seed in our nursery.</h3>
      </div>
    </div>

    <div class="row">
      <!-- Carousels -->
      <div class="col-12 col-md-6">

        <!-- Portrait Carousel (small screens) -->
        <div id="portraitCarousel10" class="carousel slide d-md-none m-5" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#portraitCarousel10" data-slide-to="0" class="active"></li>
            <li data-target="#portraitCarousel10" data-slide-to="1"></li>
            <li data-target="#portraitCarousel10" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/garden.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/corn.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/tomato/nate_and_tomato.jpg' %}" class="d-block w-100">
            </div>
          </div>
        </div>

        <!-- Landscape Carousel (md and up) -->
        <div id="landscapeCarousel10" class="carousel slide d-none d-md-block" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#landscapeCarousel10" data-slide-to="0" class="active"></li>
            <li data-target="#landscapeCarousel10" data-slide-to="1"></li>
            <li data-target="#landscapeCarousel10" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/garden02.png' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/garden.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/corn.jpg' %}" class="d-block w-100">
            </div>
          </div>
        </div>

      </div>

      <!-- Varieties List -->
      <div class="col-12 col-md-6">
        <h3 class="display-4">Available varieties.</h3>
        <h4 class="display-5">You won't find these at Home Depot!</h4>
        <ul>
          <li class="front-page-list-item">Chinese 5 Color</li>
          <li class="front-page-list-item">Buena Mulatta</li>
          <li class="front-page-list-item">Habanero</li>
          <li class="front-page-list-item">Real Deal Hybrid</li>
          <li class="front-page-list-item">Chocolate Jalape&#241;o</li>
          <li class="front-page-list-item">Aji Charapita</li>
          <li class="front-page-list-item">Aleppo</li>
          <li class="front-page-list-item">Jersey Devil Tomato</li>

        </ul>
      </div>
    </div>

  </div>
</section>

<!-- $40 Tier Section -->
<section id="forsalematureplant" class="py-5">
  <div class="container">

    <div class="row">
      <div class="col-12 text-center">
        <h2 class="display-3">$30 Tier</h2>
        <h3 class="display-5">
          Plant sold in 10-20 gallon planter with high quality soil.
          These plants are strong and healthy, guaranteed to start setting fruit soon.
        </h3>
      </div>
    </div>

    <div class="row">
		<div class="col-12 col-md-6">
			<h3 class="display-4">Available varieties.</h3>
			<h4 class="display-5">You won't find these at Home Depot!</h4>
			<ul>
			  <li class="front-page-list-item">Chinese 5 Color</li>
			  <li class="front-page-list-item">Buena Mulatta</li>
			  <li class="front-page-list-item">Habanero</li>
			  <li class="front-page-list-item">White Knight Eggplant</li>
			  <li class="front-page-list-item">Real Deal Hybrid</li>
			  <li class="front-page-list-item">Chocolate Jalape&#241;o</li>
			  <li class="front-page-list-item">Aji Charapita</li>
			  <li class="front-page-list-item">Aleppo</li>
			</ul>
		  </div>
      <div class="col-12 col-md-6">

        <!-- Portrait Carousel (small screens) -->
        <div id="portraitCarousel40" class="carousel slide d-md-none" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#portraitCarousel40" data-slide-to="0" class="active"></li>
            <li data-target="#portraitCarousel40" data-slide-to="1"></li>
            <li data-target="#portraitCarousel40" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/tomato/nate_and_tomato.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/garden.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/corn.jpg' %}" class="d-block w-100">
            </div>
          </div>
        </div>

        <!-- Landscape Carousel (md and up) -->
        <div id="landscapeCarousel40" class="carousel slide d-none d-md-block" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#landscapeCarousel40" data-slide-to="0" class="active"></li>
            <li data-target="#landscapeCarousel40" data-slide-to="1"></li>
            <li data-target="#landscapeCarousel40" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/garden02.png' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/garden.jpg' %}" class="d-block w-100">
            </div>
            <div class="carousel-item">
              <img src="{% static 'mainapp/img/corn.jpg' %}" class="d-block w-100">
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

<section id="mantises" class="py-5">
  <div class="container">

    <div class="row">
      <div class="col-12 text-center">
        <h2 class="display-3">Mantises</h2>
        <h3 class="display-5">None for sale this year, but if you come by maybe you can trap one and keep it as a pet!.</h3>
      </div>
    </div>

    <div class="row">
      <!-- Carousels -->
      <div class="col-12 col-md-6">

        <!-- Portrait Carousel (small screens) -->
        <div id="portraitCarousel10" class="carousel slide d-md-none m-5" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#portraitCarousel10" data-slide-to="0" class="active"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/mantis/mantis.png' %}" class="d-block w-100">
            </div>
          </div>
        </div>

        <!-- Landscape Carousel (md and up) -->
        <div id="landscapeCarousel10" class="carousel slide d-none d-md-block" data-ride="carousel" data-interval="4000" data-pause="false">
          <ol class="carousel-indicators">
            <li data-target="#landscapeCarousel10" data-slide-to="0" class="active"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'mainapp/img/mantis/mantis.png' %}" class="d-block w-100">
            </div>
          </div>
        </div>

      </div>

      <!-- Varieties List -->
      <div class="col-12 col-md-6">
        <h3 class="display-4">What You'll See.</h3>
        <ul>
          <li class="front-page-list-item">Carolina Mantis</li>
          <li class="front-page-list-item">Chinese Mantis</li>
          <li class="front-page-list-item">European Mantis</li>
        </ul>
      </div>
    </div>

  </div>
</section>
</body>
{% endblock %}

{% block updateActive %}
<script>
  $(document).ready(function() {
    $("#about_page_nav_item").addClass("active");
  });
</script>
{% endblock %}

cienfuegosexotics/mainapp/templates/mainapp/learning.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block body %}
<section id="header" class="mx-4">
    <div class="container h-100">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="text-center text-wrap">Learn From Us!</h1>
          <p>We've been raising tomatoes, peppers and mantises for years now. Come visit this page often to learn about our latest educational activities for you and your kids.</p>
          <p> We can teach you about how to raise mantises, and show you all kinds of cool and scary specimens! </p>
            <p> We can also teach you and your kids about grafting tomatoes to potatoes and to other tomatoes as well as other techniques to grow amazing, healthy plants.</p>
        </div>
      </div>
  </div>
</section>

{% endblock %}


{% block updateActive %}
   <script>
    $(document).ready(function() {
            var currentPage= $( "#about_page_nav_item" );    
            .addClass( "active" );
        });
    </script>
{% endblock %}

cienfuegosexotics/mainapp/templates/mainapp/mantises.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block body %}
<section id="header" class="mx-4">
    <div class="container">
    <div class="row">
        <div class="col-12">
            <h1> Mantises </h1>
            <p> One of nature's most amazing creatures. This is a bug with a personality. </p>
            <p> This creature will change your perception of insects. They love to be held and will gladly walk in your hands and on your head. They turn their heads to look at you and follow you with their gaze. </p>
            <p> It's absolutely terrifying to watch them snatch flies out of the air and devour them whole. It's like watching an African Lions eat a buffallo on National Geographic. These bugs are peaceful with humans but merciless when it comes to other bugs. </p>
            <p> A fantastic and interesting pet. They live through the summer and pass away in the fall. Stunningly beautiful, interesting, short-lived creatures. </p>
        </div>
    </div>


      <div class="row">
             <div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/mantis/mantis.png' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Carolina Mantis
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Native to the East Coast of the USA!</h5>
                    <p class="card-text">A cute mantis, about 4 inches long when fully grown. Native to the east coast of the USA</p>
              </div>
            </div>
        </div>
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/mantis/mantis.png' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Chinese Mantis
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Cool Bug</h5>
                    <p class="card-text">The Chinese mantis is similar in appearance to the Carolina Mantis, but it is a bit larger. Easy to handle. Voracious predator.</p>
              </div>
            </div>
        </div>
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/mantis/mantis.png' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    European Mantis
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">A Beauty</h5>
                    <p class="card-text">Similar in size, appearance and temperament to the Chinese Mantis. A wonderful bug.</p>
              </div>
            </div>
        </div>
   </div>
  </div>
</section>

{% endblock %}


{% block updateActive %}
   <script>
    $(document).ready(function() {
            var currentPage= $( "#peppers_page_nav_item" );    
            .addClass( "active" );
        });
    </script>
{% endblock %}

cienfuegosexotics/mainapp/templates/mainapp/peppers.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block body %}
<section id="header" class="mx-4">
    <div class="container">

     <div class="row">
        <div class="col-12">
            <h1>Peppers In Stock</h1>
            <p>We start our peppers from seed in our greenhouse in December. It's hard work. The baby plants require lots of heat, light and attention and we have to constantly fight off bug pests and plant diseases. Some plants die along the way.</p>
            <p>When you buy a plant from us, you don't need to waste time with this boring hard work of turning a seeling into a mature plant.We'll give you a big healthy plant that's almost sure to give you a huge harvest. If you take care of your plant right, it can live 3 or more years!</p>
        </div>
     </div>


      <div class="row">
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/cherry.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Hot Cherry
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Melvyn's Favorite</h5>
                    <p class="card-text">You've probably seen this pepper stuffed with Prosciutto on the deli counter. Delicious, crisp peppers with just the right amound of heat. Good for cooking, sauces, pickling, or whatever you can imagine.</p>
              </div>
            </div>
        </div>
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/reaper.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Carolina Reaper
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">The Big Dog!</h5>
                    <p class="card-text">This is the hottest pepper in the world. One pepper will be enough to last you all winter. Really a dangerous plant, don't keep this around children or pets. Proceed with caution and have fun.</p>
              </div>
            </div>
        </div>
             <div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/habanada02.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Habanada
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">It's Not Spicy!</h5>
                    <p class="card-text">A very hard to find pepper plant. Looks like a habanero pepper, you'll probably be scared to bite into one of these. But it's actually very sweet! A very interesting plant and wonderful conversation piece for your back yard.</p>
              </div>
            </div>
        </div>
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/bell_pepper.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Sweet Carolina Bell
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Delicious!</h5>
                    <p class="card-text">A delicious bell pepper. Large, sweet, firm peppers. Typically cost about $2 per pound at the grocery store, but you'll have unlimited peppers right there in your yard or on your fire escape! </p>
              </div>
            </div>
        </div>
<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/cayenne.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Dragon Cayenne
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">This one's no joke!</h5>
                    <p class="card-text">A properly spicy pepper. Long thin finger peppers, perfect for your favorite recipes or sauces.</p>
              </div>
            </div>
        </div>


<div class="col-lg-3 col-sm-6 col-xs-12 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/peppers/rainbow.jpg' %}" alt="image" class="card-img-top">
                <div class="card-header">
                    Rainbow Firecracker Chili
                </div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Don't be fooled</h5>
                    <p class="card-text">This is a beautiful plant with green/purple leaves and absolutely packed with tiny little mouth burning peppers. The plant is truly beautiful as it has the multicolor leaves and peppers that will be green, yellow, red, purple and orange. A beauty and very spicy</p>
              </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-6 text-center">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <img src="{% static 'mainapp/img/mantis/mantis.png' %}" alt="image" class="card-img-top">
                <div class="card-header">Hot Yellow Peppers</div>
                <div class="card-body text-primary">
                    <h5 class="card-title">Cool Color, Serious Heat</h5>
                    <p class="card-text">Pretty long yellow peppers. Properly spicy and pretty to look at.</p>
              </div>
            </div>
        </div>
    </div>
  </div>
</section>

{% endblock %}


{% block updateActive %}
   <script>
    $(document).ready(function() {
            var currentPage= $( "#peppers_page_nav_item" );    
            .addClass( "active" );
        });
    </script>
{% endblock %}